# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
      - feature/add-github-actions
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@master
      - run: flutter pub get
      - run: flutter test

   
