# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: wei/curl@v1.1.1
        with:
          args: curl -X POST  -d "${{ secrets.FIREBASE_API_KEY }}" https://taskee-cc10e-default-rtdb.firebaseio.com/actions.json  
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@master
      - run: echo "${{ secrets.FIREBASE_API_KEY }}" > .env
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk 

   
